import type { Metadata } from "next";
import "./globals.css";
import Providers from "./providers";
import localFont from 'next/font/local';

export const geist = localFont({
  src: [
    { path: '/fonts/Geist-Regular.woff2', weight: '400', style: 'normal' },
    { path: '/fonts/Geist-Bold.woff2', weight: '700', style: 'normal' },
  ],
  variable: '--font-geist',
  display: 'swap',
});

export const geistMono = localFont({
  src: [
    { path: '/fonts/GeistMono-Regular.woff2', weight: '400', style: 'normal' },
    { path: '/fonts/GeistMono-Bold.woff2', weight: '700', style: 'normal' },
  ],
  variable: '--font-geist-mono',
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geist.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
            {children}
          </Providers>
      </body>
    </html>
  );
}
